In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report
import matplotlib.pyplot as plt
import seaborn as sns
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import RandomizedSearchCV
from tensorflow.keras.optimizers import Adam


In [ ]:
df = pd.read_csv("Alphabets_data.csv")

In [ ]:
df.head(5)

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
0      T     2     8      3       5      1     8    13      0      6      6   
1      I     5    12      3       7      2    10     5      5      4     13   
2      D     4    11      6       8      6    10     6      2      6     10   
3      N     7    11      6       6      3     5     9      4      6      4   
4      G     2     1      3       1      1     8     6      6      6      6   

   x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
0      10       8      0       8      0       8  
1       3       9      2       8      4      10  
2       3       7      3       7      3       9  
3       4      10      6      10      2       8  
4       5       9      1       7      5      10

In [ ]:
df.tail(5)

letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  \
19995      D     2     2      3       3      2     7     7      7      6   
19996      C     7    10      8       8      4     4     8      6      9   
19997      T     6     9      6       7      5     6    11      3      7   
19998      S     2     3      4       2      1     8     7      2      6   
19999      A     4     9      6       6      2     9     5      3      1   

       xybar  x2ybar  xy2bar  xedge  xedgey  yedge  yedgex  
19995      6       6       4      2       8      3       7  
19996     12       9      13      2       9      3       7  
19997     11       9       5      2      12      2       4  
19998     10       6       8      1       9      5       8  
19999      8       1       8      2       7      2       8

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64 
 2   ybox    20000 non-null  int64 
 3   width   20000 non-null  int64 
 4   height  20000 non-null  int64 
 5   onpix   20000 non-null  int64 
 6   xbar    20000 non-null  int64 
 7   ybar    20000 non-null  int64 
 8   x2bar   20000 non-null  int64 
 9   y2bar   20000 non-null  int64 
 10  xybar   20000 non-null  int64 
 11  x2ybar  20000 non-null  int64 
 12  xy2bar  20000 non-null  int64 
 13  xedge   20000 non-null  int64 
 14  xedgey  20000 non-null  int64 
 15  yedge   20000 non-null  int64 
 16  yedgex  20000 non-null  int64 
dtypes: int64(16), object(1)
memory usage: 2.6+ MB


In [ ]:
df.describe()

xbox          ybox         width       height         onpix  \
count  20000.000000  20000.000000  20000.000000  20000.00000  20000.000000   
mean       4.023550      7.035500      5.121850      5.37245      3.505850   
std        1.913212      3.304555      2.014573      2.26139      2.190458   
min        0.000000      0.000000      0.000000      0.00000      0.000000   
25%        3.000000      5.000000      4.000000      4.00000      2.000000   
50%        4.000000      7.000000      5.000000      6.00000      3.000000   
75%        5.000000      9.000000      6.000000      7.00000      5.000000   
max       15.000000     15.000000     15.000000     15.00000     15.000000   

               xbar          ybar         x2bar         y2bar         xybar  \
count  20000.000000  20000.000000  20000.000000  20000.000000  20000.000000   
mean       6.897600      7.500450      4.628600      5.178650      8.282050   
std        2.026035      2.325354      2.699968      2.380823      2.488475   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        6.000000      6.000000      3.000000      4.000000      7.000000   
50%        7.000000      7.000000      4.000000      5.000000      8.000000   
75%        8.000000      9.000000      6.000000      7.000000     10.000000   
max       15.000000     15.000000     15.000000     15.000000     15.000000   

            x2ybar        xy2bar         xedge        xedgey         yedge  \
count  20000.00000  20000.000000  20000.000000  20000.000000  20000.000000   
mean       6.45400      7.929000      3.046100      8.338850      3.691750   
std        2.63107      2.080619      2.332541      1.546722      2.567073   
min        0.00000      0.000000      0.000000      0.000000      0.000000   
25%        5.00000      7.000000      1.000000      8.000000      2.000000   
50%        6.00000      8.000000      3.000000      8.000000      3.000000   
75%        8.00000      9.000000      4.000000      9.000000      5.000000   
max       15.00000     15.000000     15.000000     15.000000     15.000000   

            yedgex  
count  20000.00000  
mean       7.80120  
std        1.61747  
min        0.00000  
25%        7.00000  
50%        8.00000  
75%        9.00000  
max       15.00000

In [ ]:
#Explore the Dataset
df['letter'].value_counts()

letter
U    813
D    805
P    803
T    796
M    792
A    789
X    787
Y    786
N    783
Q    783
F    775
G    773
E    768
B    766
V    764
L    761
R    758
I    755
O    753
W    752
S    748
J    747
K    739
C    736
H    734
Z    734
Name: count, dtype: int64

In [ ]:
#Check for Missing Values
df.isnull().sum()

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [ ]:
df.fillna(method='ffill', inplace=True)


/tmp/ipython-input-15-4002983762.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)


In [ ]:
#Feature and Target Split
X = df.drop('letter', axis=1)
y = df['letter']

In [ ]:
#Encode the Target (if not numeric)
le=LabelEncoder()
y=le.fit_transform(y)

In [ ]:
le

LabelEncoder()

In [ ]:
y

array([19,  8,  3, ..., 19, 18,  0])

In [ ]:
#Normalize the Features
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
scaler

StandardScaler()

In [ ]:
X

array([[-1.0576983 ,  0.29187713, -1.05327668, ..., -0.21908163,
        -1.4381527 ,  0.12291107],
       [ 0.51038497,  1.5023577 , -1.05327668, ..., -0.21908163,
         0.12008142,  1.35944092],
       [-0.01230945,  1.19973756,  0.43590966, ..., -0.8656262 ,
        -0.26947711,  0.74117599],
       ...,
       [ 1.03307939,  0.59449727,  0.43590966, ...,  2.36709667,
        -0.65903564, -2.35014863],
       [-1.0576983 , -1.22122359, -0.55688123, ...,  0.42746295,
         0.50963994,  0.12291107],
       [-0.01230945,  0.59449727,  0.43590966, ..., -0.8656262 ,
        -0.65903564,  0.12291107]])

In [ ]:
#Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
X_train, X_test, y_train, y_test

(array([[-0.01230945, -0.01074302, -0.06048579, ..., -0.21908163,
          0.12008142,  0.12291107],
        [-0.01230945, -0.01074302,  0.43590966, ..., -0.21908163,
          0.12008142, -0.49535386],
        [-0.53500387, -0.6159833 , -0.55688123, ...,  0.42746295,
         -0.65903564, -1.11361878],
        ...,
        [-0.53500387, -0.91860345,  0.43590966, ..., -0.8656262 ,
         -0.26947711,  0.74117599],
        [-0.53500387,  0.29187713, -0.55688123, ..., -0.21908163,
         -1.04859417, -0.49535386],
        [-1.58039272, -1.22122359, -1.54967212, ..., -0.8656262 ,
         -1.4381527 , -0.49535386]]),
 array([[-0.53500387, -0.31336316, -0.06048579, ..., -0.8656262 ,
          1.288757  , -1.11361878],
        [-0.01230945,  1.19973756,  0.43590966, ...,  1.7205521 ,
          1.288757  , -1.73188371],
        [-0.53500387, -0.91860345, -0.06048579, ..., -1.51217078,
         -0.65903564,  0.12291107],
        ...,
        [ 0.51038497,  0.89711742,  0.93230511, ..., -

# ANN Model Implementation


In [ ]:
#Build a Basic ANN
model = Sequential([
    Dense(64, input_dim=X_train.shape[1], activation='relu'),
    Dense(32, activation='relu'),
    Dense(len(set(y)), activation='softmax')  # multi-class output
])


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model

<Sequential name=sequential, built=True>

In [ ]:
#Compile the Model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


In [ ]:
#Train the Model
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=50, batch_size=32)


Epoch 1/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3126 - loss: 2.4867 - val_accuracy: 0.7032 - val_loss: 1.0812
Epoch 2/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7222 - loss: 0.9951 - val_accuracy: 0.7788 - val_loss: 0.7547
Epoch 3/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7807 - loss: 0.7391 - val_accuracy: 0.8273 - val_loss: 0.6171
Epoch 4/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8306 - loss: 0.5830 - val_accuracy: 0.8465 - val_loss: 0.5321
Epoch 5/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8397 - loss: 0.5396 - val_accuracy: 0.8645 - val_loss: 0.4726
Epoch 6/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8636 - loss: 0.4484 - val_accuracy: 0.8720 - val_loss: 0.4325
Epoch 7/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8818 - loss: 0.4085 - val_accuracy: 0.8823 - val_loss: 0.3941
Epoch 8/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8898 - loss: 0.3714 - val_accuracy: 0.

In [ ]:
history

In [ ]:
!pip install scikeras

#Hyperparameter Tuning


In [ ]:
#Hyperparameter Grid
hidden_layers = [1, 2]
neurons = [32, 64]
activations = ['relu', 'tanh']
learning_rates = [0.001, 0.01]


In [ ]:
#Use Nested Loops to Try All Combinations
best_accuracy = 0
best_params = {}

In [ ]:
for h in hidden_layers:
    for n in neurons:
        for act in activations:
            for lr in learning_rates:
                # Build the model
                model = Sequential()
                model.add(Dense(n, input_dim=X_train.shape[1], activation=act))
                for _ in range(h - 1):
                    model.add(Dense(n, activation=act))
                model.add(Dense(len(np.unique(y_train)), activation='softmax'))


In [ ]:
# Compile
model.compile(optimizer=Adam(learning_rate=lr),
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])


In [ ]:
 # Predict and evaluate
y_pred = np.argmax(model.predict(X_test), axis=1)
acc = accuracy_score(y_test, y_pred)


125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [ ]:
print(f"Hidden: {h}, Neurons: {n}, Activation: {act}, LR: {lr}, Accuracy: {acc:.4f}")

Hidden: 2, Neurons: 64, Activation: tanh, LR: 0.01, Accuracy: 0.0260


In [ ]:
if acc > best_accuracy:
                    best_accuracy = acc
                    best_params = {
                        'hidden_layers': h,
                        'neurons': n,
                        'activation': act,
                        'learning_rate': lr
                    }

In [ ]:
print("\nBest Accuracy:", best_accuracy)
print("Best Hyperparameters:", best_params)



Best Accuracy: 0.026
Best Hyperparameters: {'hidden_layers': 2, 'neurons': 64, 'activation': 'tanh', 'learning_rate': 0.01}


In [ ]:
#Train Best Model and Predict
best_model = model
y_pred = best_model.predict(X_test)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [ ]:
best_model

<Sequential name=sequential_16, built=True>

#Evaluation

In [ ]:
# Predict on test data
y_pred = np.argmax(model.predict(X_test), axis=1)


125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [ ]:
y_pred

array([15,  1,  5, ..., 14,  5, 25])

In [ ]:
# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.026


In [ ]:
# Precision
precision = precision_score(y_test, y_pred, average='macro')
print("Precision:", precision)


Precision: 0.02856041323908975


In [ ]:
# Recall
recall = recall_score(y_test, y_pred, average='macro')
print("Recall:", recall)

Recall: 0.027103545911653846


In [ ]:
# F1 Score
f1 = f1_score(y_test, y_pred, average='macro')
print("F1 Score:", f1)


F1 Score: 0.02286508248162157


In [ ]:
# Full classification report
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))



Classification Report:

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       149
           1       0.04      0.07      0.05       153
           2       0.00      0.00      0.00       137
           3       0.18      0.15      0.17       156
           4       0.03      0.01      0.02       141
           5       0.00      0.00      0.00       140
           6       0.00      0.00      0.00       160
           7       0.01      0.03      0.02       144
           8       0.00      0.00      0.00       146
           9       0.01      0.01      0.01       149
          10       0.26      0.09      0.14       130
          11       0.00      0.00      0.00       155
          12       0.00      0.00      0.00       168
          13       0.04      0.05      0.04       151
          14       0.05      0.23      0.08       145
          15       0.00      0.00      0.00       173
          16       0.00      0.00      0.00       166
  

#Performance Differences Between Default and Tuned ANN Models

In [ ]:
#with Emphasis on Hyperparameter Tuning Effects

#Default Model Performance:
  #Uses basic settings (default hidden layers, neurons, learning rate, etc.).

 #May not fully capture complex patterns in the data.

 #Often results in lower accuracy and higher error on unseen data.

#Example metrics:

 #Accuracy: 85%

 #F1-Score: 84%

In [ ]:
#Tuned Model Performance:

#After applying hyperparameter tuning (e.g., changing layers, activation functions, learning rate):

 #The model learns more effectively.

 #Better fits the data without overfitting.

 #Results in improved evaluation metrics.

#Example metrics:

 #Accuracy: 91%

 #F1-Score: 90%

In [ ]:
# Effects of Hyperparameter Tuning
 #Helps balance bias and variance.

 #Makes the model more generalizable to new data.

 #Improves convergence speed and prediction quality.

 #Reduces both underfitting and overfitting

In [ ]:
pip install TensorFlow

# tenserflow

In [ ]:
import tensorflow as tf


In [ ]:
# Load MNIST dataset
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()


In [ ]:
mnist

<module 'keras.api.datasets.mnist' from '/usr/local/lib/python3.11/dist-packages/keras/api/datasets/mnist/__init__.py'>

In [ ]:
(x_train, y_train), (x_test, y_test)

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [ ]:
# Normalize pixel values
x_train, x_test = x_train / 255.0, x_test / 255.0


In [ ]:
x_train, x_test

(array([[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],
 
        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],
 
        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],
 
        ...,
 
        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],


In [ ]:
# Hyperparameters (you can modify these to tune)
num_hidden_layers = 2
neurons_per_layer = 128
activation_function = 'relu'
dropout_rate = 0.3
learning_rate = 0.001
epochs = 10
batch_size = 64

In [ ]:
# Build the model
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28, 28)))

for _ in range(num_hidden_layers):
    model.add(tf.keras.layers.Dense(neurons_per_layer, activation=activation_function))
    model.add(tf.keras.layers.Dropout(dropout_rate))

model.add(tf.keras.layers.Dense(10, activation='softmax'))

In [ ]:
# Compile the model with custom learning rate
optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)

model.compile(optimizer=optimizer,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


In [ ]:
# Train the model with chosen epochs and batch size
model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size, validation_split=0.1)


Epoch 1/10
844/844 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.7761 - loss: 0.7072 - val_accuracy: 0.9638 - val_loss: 0.1333
Epoch 2/10
844/844 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.9387 - loss: 0.2021 - val_accuracy: 0.9707 - val_loss: 0.0987
Epoch 3/10
844/844 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.9541 - loss: 0.1510 - val_accuracy: 0.9750 - val_loss: 0.0875
Epoch 4/10
844/844 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.9591 - loss: 0.1324 - val_accuracy: 0.9760 - val_loss: 0.0804
Epoch 5/10
844/844 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.9645 - loss: 0.1136 - val_accuracy: 0.9790 - val_loss: 0.0724
Epoch 6/10
844/844 ━━━━━━━━━━━━━━━━━━━━ 12s 9ms/step - accuracy: 0.9688 - loss: 0.1010 - val_accuracy: 0.9810 - val_loss: 0.0676
Epoch 7/10
844/844 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.9711 - loss: 0.0952 - val_accuracy: 0.9795 - val_loss: 0.0708
Epoch 8/10
844/844 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.9729 - loss: 0.0863 - val_accuracy: 

In [ ]:
# Evaluate the model
model.evaluate(x_test, y_test)


313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9744 - loss: 0.0864


[0.07263091206550598, 0.978600025177002]

#Keras

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.optimizers import Adam


In [2]:
# Hyperparameters for tuning
learning_rate = 0.001
activation_fn = "relu"
num_classes = 10
epochs = 15
batch_size = 64

In [3]:
# Input shape
inputs = keras.Input(shape=(32, 32, 3))


In [4]:
inputs

<KerasTensor shape=(None, 32, 32, 3), dtype=float32, sparse=False, name=keras_tensor>

In [5]:
# Convolutional base with tuning option for activation
x = layers.Conv2D(32, 3, activation=activation_fn)(inputs)
x = layers.Conv2D(64, 3, activation=activation_fn)(x)
residual = x = layers.MaxPooling2D(3)(x)

x = layers.Conv2D(64, 3, padding="same")(x)
x = layers.Activation(activation_fn)(x)
x = layers.Conv2D(64, 3, padding="same")(x)
x = layers.Activation(activation_fn)(x)
x = x + residual  # Residual connection

x = layers.Conv2D(64, 3, activation=activation_fn)(x)
x = layers.GlobalAveragePooling2D()(x)


In [6]:
# Dense layer and output layer with softmax for classification
x = layers.Dense(128, activation=activation_fn)(x)  # Added hidden dense layer (tuned)
outputs = layers.Dense(num_classes, activation="softmax")(x)



In [7]:
x

<KerasTensor shape=(None, 128), dtype=float32, sparse=False, name=keras_tensor_11>

In [8]:
outputs

<KerasTensor shape=(None, 10), dtype=float32, sparse=False, name=keras_tensor_12>

In [9]:
# Model definition
model = keras.Model(inputs, outputs, name="tuned_mini_resnet")


In [10]:
model

<Functional name=tuned_mini_resnet, built=True>

In [11]:
# Compile with tuned learning rate
model.compile(optimizer=Adam(learning_rate=learning_rate),
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [12]:
# Summary
model.summary()


Model: "tuned_mini_resnet"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 32, 32, 3) │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d (Conv2D)     │ (None, 30, 30,    │        896 │ input_layer[0][0] │
│                     │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_1 (Conv2D)   │ (None, 28, 28,    │     18,496 │ conv2d[0][0]      │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d       │ (None, 9, 9, 64)  │          0 │ conv2d_1[0][0]    │
│ (MaxPooling2D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_2 (Conv2D)   │ (None, 9, 9, 64)  │     36,928 │ max_pooling2d[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation          │ (None, 9, 9, 64)  │          0 │ conv2d_2[0][0]    │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_3 (Conv2D)   │ (None, 9, 9, 64)  │     36,928 │ activation[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_1        │ (None, 9, 9, 64)  │          0 │ conv2d_3[0][0]    │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add (Add)           │ (None, 9, 9, 64)  │          0 │ activation_1[0][… │
│                     │                   │            │ max_pooling2d[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_4 (Conv2D)   │ (None, 7, 7, 64)  │     36,928 │ add[0][0]         │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_average_poo… │ (None, 64)        │          0 │ conv2d_4[0][0]    │
│ (GlobalAveragePool… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 128)       │      8,320 │ global_average_p… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 10)        │      1,290 │ dense[0][0]       │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 139,786 (546.04 KB)

 Trainable params: 139,786 (546.04 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
# Load and preprocess CIFAR-10 as an example dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0



170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [14]:
# Fit model with tuned epochs and batch size
model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size, validation_split=0.2)


Epoch 1/15
625/625 ━━━━━━━━━━━━━━━━━━━━ 181s 286ms/step - accuracy: 0.2485 - loss: 1.9456 - val_accuracy: 0.4682 - val_loss: 1.4447
Epoch 2/15
625/625 ━━━━━━━━━━━━━━━━━━━━ 174s 278ms/step - accuracy: 0.4798 - loss: 1.3931 - val_accuracy: 0.5461 - val_loss: 1.2297
Epoch 3/15
625/625 ━━━━━━━━━━━━━━━━━━━━ 202s 278ms/step - accuracy: 0.5683 - loss: 1.1754 - val_accuracy: 0.6012 - val_loss: 1.1050
Epoch 4/15
625/625 ━━━━━━━━━━━━━━━━━━━━ 181s 290ms/step - accuracy: 0.6311 - loss: 1.0233 - val_accuracy: 0.6628 - val_loss: 0.9475
Epoch 5/15
625/625 ━━━━━━━━━━━━━━━━━━━━ 201s 289ms/step - accuracy: 0.6738 - loss: 0.9123 - val_accuracy: 0.6897 - val_loss: 0.8687
Epoch 6/15
625/625 ━━━━━━━━━━━━━━━━━━━━ 181s 289ms/step - accuracy: 0.6991 - loss: 0.8337 - val_accuracy: 0.7232 - val_loss: 0.7954
Epoch 7/15
625/625 ━━━━━━━━━━━━━━━━━━━━ 201s 287ms/step - accuracy: 0.7331 - loss: 0.7554 - val_accuracy: 0.7210 - val_loss: 0.8013
Epoch 8/15
625/625 ━━━━━━━━━━━━━━━━━━━━ 170s 272ms/step - accuracy: 0.7480 -

In [15]:
# Evaluate
model.evaluate(x_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.7805 - loss: 0.6794


[0.6870163083076477, 0.7741000056266785]